const baseUrl = "https://www.verkoopjehuisdirect.nl";

const routes = [
  ["/", 1],
  ["/huis-direct-verkopen", 0.9],
  ["/huis-snel-verkopen", 0.9],
  ["/woning-verkopen-zonder-makelaar", 0.88],
  ["/opknapwoning-verkopen", 0.88],
  ["/leegstaand-huis-verkopen", 0.86],
  ["/huis-verkopen-zonder-leeghalen", 0.84],
  ["/huis-verkopen-zonder-opknappen", 0.84],
  ["/woning-verkopen-die-nog-vol-staat", 0.84],
  ["/geerfde-woning-verkopen-zonder-leeghalen", 0.82],
  ["/opknapwoning-verkopen-zonder-makelaar", 0.82],
  ["/leegstaand-huis-verkopen-wat-zijn-de-opties", 0.82],
  ["/huis-verkopen-bij-dubbele-lasten", 0.82],
  ["/huis-verkopen-zonder-bezichtigingen-uitleg", 0.82],
  ["/huis-verkopen-binnen-24-uur", 0.8],
  ["/huis-verkopen-binnen-1-week", 0.8],
  ["/huis-verkopen-zonder-bezichtigingen", 0.8],
  ["/woning-verkopen-zonder-open-huis", 0.8],
  ["/huis-verkopen-zonder-funda", 0.8],
  ["/huis-verkopen-zonder-verkoopklaar-maken", 0.8],
  ["/woning-verkopen-met-schade", 0.8],
  ["/huis-verkopen-met-spoed", 0.8],
  ["/huis-verkopen-na-overlijden", 0.8],
  ["/huis-verkopen-bij-scheiding", 0.78],
  ["/huis-verkopen-aan-opkoper", 0.78],
  ["/huis-verkopen-bij-erfenis", 0.78],
  ["/huis-verkopen-met-achterstallig-onderhoud", 0.78],
  ["/verhuurde-woning-verkopen", 0.78],
  ["/huis-verkopen-groningen", 0.76],
  ["/woning-verkopen-drenthe", 0.74],
  ["/woning-verkopen-friesland", 0.74],
  ["/woning-verkopen-overijssel", 0.74],
  ["/huis-verkopen-stadskanaal", 0.72],
  ["/huis-verkopen-veendam", 0.72],
  ["/huis-verkopen-winschoten", 0.72],
  ["/huis-verkopen-assen", 0.72],
  ["/huis-verkopen-emmen", 0.72],
  ["/huis-verkopen-borger", 0.72],
  ["/huis-verkopen-gieten", 0.72],
  ["/privacyverklaring", 0.3],
];

export default function sitemap() {
  return routes.map(([path, priority]) => ({
    url: `${baseUrl}${path === "/" ? "" : path}`,
    lastModified: new Date(),
    changeFrequency: path === "/" ? "weekly" : "monthly",
    priority,
  }));
}
